name = "FunSQL"
uuid = "cf6cc811-59f4-4a10-b258-a8547a8f6407"
authors = ["Kirill Simonov <xi@resolvent.net>", "Clark C. Evans <cce@clarkevans.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PrettyPrinting = "54e16d92-306c-5ea0-a30b-337be88ac337"

[compat]
julia = "1.4"
PrettyPrinting = "0.3"

[extras]
NarrativeTest = "9563631e-acd4-5dd8-bebb-4cf36518960d"

[targets]
test = ["NarrativeTest"]
